### ISSUE TITLE
Can't working with iPad 2,2  A5  purple model  

### ISSUE THREAD

**Issue by haoerloveyou** [j4nf4b3l/MagicCFG-Reloaded#1]
today I test MagicCFG V2.0 . I find that the tool still not work with iPad2,2 A5 . Can't read SysCFG. iPad 2 is  already in purple model and it connect with computer  by DCSD(ALEX) line. Waiting  to Fix the bug . thanks

**Comment by j4nf4b3l** [comment]
This is a problem related to your iPad model. Purple mode works fine but do not detect the NAND correctly... Nothing I can fix here in code of MagicCFG... 
I'm sorry :/
